Repository LXD-UMC-8th/BE-LXD, pull requests merged in 2025-09, with the labels that each got.

#269 [FEATURE] 댓글 삭제 권한 검증 추가 및 Guard 적용
  src/main/java/org/lxdproject/lxd/apiPayload/code/status/ErrorStatus.java
  src/main/java/org/lxdproject/lxd/authz/guard/PermissionGuard.java
  src/main/java/org/lxdproject/lxd/authz/policy/CommentPermissionPolicy.java
  src/main/java/org/lxdproject/lxd/correctioncomment/service/CorrectionCommentService.java
  src/main/java/org/lxdproject/lxd/diarycomment/service/DiaryCommentService.java
Labels: ✨feat, 슝슝/소윤

#270 [FEATURE] 회원 탈퇴 구현
  build.gradle
  src/main/java/org/lxdproject/lxd/LxdApplication.java
  src/main/java/org/lxdproject/lxd/apiPayload/code/exception/ExceptionAdvice.java
  src/main/java/org/lxdproject/lxd/apiPayload/code/status/ErrorStatus.java
  src/main/java/org/lxdproject/lxd/auth/controller/AuthApi.java
  src/main/java/org/lxdproject/lxd/auth/controller/AuthController.java
  src/main/java/org/lxdproject/lxd/auth/converter/AuthConverter.java
  src/main/java/org/lxdproject/lxd/auth/dto/AuthResponseDTO.java
  src/main/java/org/lxdproject/lxd/auth/dto/CustomUserDetails.java
  src/main/java/org/lxdproject/lxd/auth/filter/WithdrawnAccountFilter.java
  src/main/java/org/lxdproject/lxd/auth/service/AuthService.java
  src/main/java/org/lxdproject/lxd/auth/service/CustomUserDetailsService.java
  src/main/java/org/lxdproject/lxd/authz/guard/PermissionGuard.java
  src/main/java/org/lxdproject/lxd/authz/model/Permit.java
  src/main/java/org/lxdproject/lxd/authz/policy/DiaryVisibilityPolicy.java
  src/main/java/org/lxdproject/lxd/authz/policy/FriendPolicy.java
  src/main/java/org/lxdproject/lxd/authz/predicate/VisibilityPredicates.java
  src/main/java/org/lxdproject/lxd/common/dto/MemberProfileDTO.java
  src/main/java/org/lxdproject/lxd/common/entity/BaseEntity.java
  src/main/java/org/lxdproject/lxd/config/SchedulerConfig.java
  src/main/java/org/lxdproject/lxd/config/security/SecurityConfig.java
  src/main/java/org/lxdproject/lxd/config/security/SecurityUtil.java
  src/main/java/org/lxdproject/lxd/config/security/jwt/JwtTokenProvider.java
  src/main/java/org/lxdproject/lxd/correction/dto/CorrectionResponseDTO.java
  src/main/java/org/lxdproject/lxd/correction/service/CorrectionService.java
  src/main/java/org/lxdproject/lxd/correctioncomment/dto/CorrectionCommentResponseDTO.java
  src/main/java/org/lxdproject/lxd/correctioncomment/service/CorrectionCommentService.java
  src/main/java/org/lxdproject/lxd/correctionlike/dto/MemberSavedCorrectionResponseDTO.java
  src/main/java/org/lxdproject/lxd/correctionlike/service/MemberSavedCorrectionService.java
  src/main/java/org/lxdproject/lxd/diary/dto/DiaryDetailResponseDTO.java
  src/main/java/org/lxdproject/lxd/diary/dto/DiarySummaryResponseDTO.java
  src/main/java/org/lxdproject/lxd/diary/dto/MemberDiarySummaryResponseDTO.java
  src/main/java/org/lxdproject/lxd/diary/repository/DiaryRepository.java
  src/main/java/org/lxdproject/lxd/diary/repository/DiaryRepositoryImpl.java
  src/main/java/org/lxdproject/lxd/diary/service/DiaryService.java
  src/main/java/org/lxdproject/lxd/diarycomment/converter/DiaryCommentConverter.java
  src/main/java/org/lxdproject/lxd/diarycomment/dto/DiaryCommentResponseDTO.java
  src/main/java/org/lxdproject/lxd/diarycomment/repository/DiaryCommentRepository.java
  src/main/java/org/lxdproject/lxd/diarycomment/repository/DiaryCommentRepositoryCustom.java
  src/main/java/org/lxdproject/lxd/diarycomment/repository/DiaryCommentRepositoryImpl.java
  src/main/java/org/lxdproject/lxd/diarycomment/service/DiaryCommentService.java
  src/main/java/org/lxdproject/lxd/diarycommentlike/dto/DiaryCommentLikeResponseDTO.java
  src/main/java/org/lxdproject/lxd/diarycommentlike/repository/DiaryCommentLikeRepository.java
  src/main/java/org/lxdproject/lxd/diarycommentlike/service/DiaryCommentLikeService.java
  src/main/java/org/lxdproject/lxd/diarylike/dto/DiaryLikeResponseDTO.java
  src/main/java/org/lxdproject/lxd/diarylike/entity/DiaryLike.java
  src/main/java/org/lxdproject/lxd/diarylike/repository/DiaryLikeRepository.java
  src/main/java/org/lxdproject/lxd/diarylike/service/DiaryLikeService.java
  src/main/java/org/lxdproject/lxd/friend/service/FriendService.java
  src/main/java/org/lxdproject/lxd/member/controller/MemberApi.java
  src/main/java/org/lxdproject/lxd/member/controller/MemberController.java
  src/main/java/org/lxdproject/lxd/member/entity/Member.java
  src/main/java/org/lxdproject/lxd/member/repository/MemberRepository.java
  src/main/java/org/lxdproject/lxd/member/service/MemberService.java
  src/main/java/org/lxdproject/lxd/schedular/MemberCleanupSchedular.java
  src/main/java/org/lxdproject/lxd/schedular/entity/ShedLock.java
  src/test/java/org/lxdproject/lxd/member/MemberServiceTest.java
Labels: ✨feat

#276 [FIX] 일기 상세조회시 좋아요 여부 필드 추가
  src/main/java/org/lxdproject/lxd/diary/dto/DiaryDetailResponseDTO.java
  src/main/java/org/lxdproject/lxd/diary/service/DiaryService.java
Labels: 🐛fix, 슝슝/소윤

#282 [FIX] redis 이메일 조회 시 발생하는 에러 처리
  src/main/java/org/lxdproject/lxd/auth/service/AuthService.java
  src/main/java/org/lxdproject/lxd/infra/redis/RedisService.java
Labels: 🐛fix

#283 [FEAT] 비밀번호 변경을 위한 이메일 인증 후 리다이렉트 uri 변경
  src/main/java/org/lxdproject/lxd/auth/service/AuthService.java
Labels: ✨feat
