Repository LXD-UMC-8th/BE-LXD, pull requests merged in 2025-07, with the labels that each got.

#11 [FEATURE] Member Entity 생성
  src/main/java/org/lxdproject/lxd/member/entity/Member.java
  src/main/java/org/lxdproject/lxd/member/entity/enums/LoginType.java
  src/main/java/org/lxdproject/lxd/member/entity/enums/Role.java
  src/main/java/org/lxdproject/lxd/member/entity/enums/Status.java
Labels: ✨feat, 밤하늘/준현

#14 [FEATURE] 회원가입 API 구현
  build.gradle
  src/main/java/org/lxdproject/lxd/apiPayload/code/exception/handler/MemberHandler.java
  src/main/java/org/lxdproject/lxd/apiPayload/code/status/ErrorStatus.java
  src/main/java/org/lxdproject/lxd/member/controller/MemberRestController.java
  src/main/java/org/lxdproject/lxd/member/converter/MemberConverter.java
  src/main/java/org/lxdproject/lxd/member/dto/MemberRequestDTO.java
  src/main/java/org/lxdproject/lxd/member/dto/MemberResponseDTO.java
  src/main/java/org/lxdproject/lxd/member/repository/MemberRepository.java
  src/main/java/org/lxdproject/lxd/member/service/MemberService.java
Labels: ✨feat, 밤하늘/준현

#24 [FEATURE] Notification Entity 생성
  src/main/java/org/lxdproject/lxd/notification/entity/Notification.java
  src/main/java/org/lxdproject/lxd/notification/entity/enums/NotificationType.java
  src/main/java/org/lxdproject/lxd/notification/entity/enums/TargetType.java
Labels: ✨feat, 슝슝/소윤

#25 [FEATURE] 일기 작성, 상세조회 세부구현 완료
  src/main/java/org/lxdproject/lxd/diary/controller/DiaryApi.java
  src/main/java/org/lxdproject/lxd/diary/controller/DiaryController.java
  src/main/java/org/lxdproject/lxd/diary/dto/DiaryDetailResponseDTO.java
  src/main/java/org/lxdproject/lxd/diary/dto/DiaryRequestDTO.java
  src/main/java/org/lxdproject/lxd/diary/dto/DiaryResponseDTO.java
  src/main/java/org/lxdproject/lxd/diary/entity/Diary.java
  src/main/java/org/lxdproject/lxd/diary/service/DiaryService.java
Labels: ✨feat, 슝슝/소윤

#28 [FEATURE] Member 엔티티 수정
  src/main/java/org/lxdproject/lxd/member/entity/Member.java
Labels: ✨feat, 밤하늘/준현

#27 [FIX] .env 파일을 >>로 계속 append 하여 중복되는 문제 해결
  .github/workflows/deploy.yml
Labels: ♻️Refactor, 슝슝/소윤

#45 [FEATURE] 랜덤 질문 조회 API 구현
  .gitignore
  src/main/java/org/lxdproject/lxd/diary/controller/DiaryApi.java
  src/main/java/org/lxdproject/lxd/diary/controller/DiaryController.java
  src/main/java/org/lxdproject/lxd/diary/dto/QuestionResponseDTO.java
  src/main/java/org/lxdproject/lxd/diary/repository/QuestionRepository.java
  src/main/java/org/lxdproject/lxd/diary/service/QuestionService.java
Labels: ✨feat, 만두/민지

#44 [FEATURE] 이메일 인증 API 구현
  build.gradle
  src/main/java/org/lxdproject/lxd/apiPayload/code/exception/handler/MailHandler.java
  src/main/java/org/lxdproject/lxd/apiPayload/code/status/ErrorStatus.java
  src/main/java/org/lxdproject/lxd/auth/controller/AuthRestController.java
  src/main/java/org/lxdproject/lxd/auth/dto/AuthRequestDTO.java
  src/main/java/org/lxdproject/lxd/auth/service/AuthService.java
  src/main/java/org/lxdproject/lxd/config/email/EmailConfig.java
  src/main/java/org/lxdproject/lxd/config/properties/UrlProperties.java
  src/main/java/org/lxdproject/lxd/config/redis/RedisConfig.java
  src/main/java/org/lxdproject/lxd/config/security/SecurityConfig.java
  src/main/java/org/lxdproject/lxd/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/org/lxdproject/lxd/config/security/jwt/JwtConstants.java
  src/main/java/org/lxdproject/lxd/config/security/jwt/JwtProperties.java
  src/main/java/org/lxdproject/lxd/config/security/jwt/JwtTokenProvider.java
  src/main/java/org/lxdproject/lxd/infra/mail/MailService.java
  src/main/java/org/lxdproject/lxd/infra/redis/RedisService.java
  src/main/resources/templates/email.html
Labels: ✨feat, 밤하늘/준현

#60 [CHORE] QueryDSL 설정 추가
  build.gradle
Labels: 📦 chore, 만두/민지

#50 [REFACTOR] 일기 삭제 세부구현 완료
  src/main/java/org/lxdproject/lxd/apiPayload/code/status/ErrorStatus.java
  src/main/java/org/lxdproject/lxd/common/util/S3Uploader.java
  src/main/java/org/lxdproject/lxd/diary/controller/DiaryApi.java
  src/main/java/org/lxdproject/lxd/diary/dto/DiaryDetailResponseDTO.java
  src/main/java/org/lxdproject/lxd/diary/dto/DiaryRequestDTO.java
  src/main/java/org/lxdproject/lxd/diary/service/DiaryService.java
  src/main/java/org/lxdproject/lxd/validation/annotation/MaxImageCount.java
  src/main/java/org/lxdproject/lxd/validation/validator/MaxImageCountValidator.java
Labels: ♻️Refactor, 슝슝/소윤

#55 [FEATURE] 일기 교정 조회 API 구현
  src/main/java/org/lxdproject/lxd/correction/controller/CorrectionApi.java
  src/main/java/org/lxdproject/lxd/correction/controller/CorrectionRestController.java
  src/main/java/org/lxdproject/lxd/correction/dto/CorrectionResponseDTO.java
  src/main/java/org/lxdproject/lxd/correction/entity/mapping/MemberSavedCorrection.java
  src/main/java/org/lxdproject/lxd/correction/repository/CorrectionRepository.java
  src/main/java/org/lxdproject/lxd/correction/repository/MemberSavedCorrectionRepository.java
  src/main/java/org/lxdproject/lxd/correction/service/CorrectionService.java
Labels: ✨feat, ♻️Refactor, 서머/서현

#75 [FEATURE] 좋아요한 교정 내 메모 CUD API 구현
  src/main/java/org/lxdproject/lxd/apiPayload/code/exception/handler/CorrectionHandler.java
  src/main/java/org/lxdproject/lxd/apiPayload/code/status/ErrorStatus.java
  src/main/java/org/lxdproject/lxd/correction/controller/CorrectionRestController.java
  src/main/java/org/lxdproject/lxd/correction/controller/MemberSavedCorrectionApi.java
  src/main/java/org/lxdproject/lxd/correction/controller/MemberSavedCorrectionController.java
  src/main/java/org/lxdproject/lxd/correction/dto/CorrectionResponseDTO.java
  src/main/java/org/lxdproject/lxd/correction/dto/MemberSavedCorrectionRequestDTO.java
  src/main/java/org/lxdproject/lxd/correction/dto/MemberSavedCorrectionResponseDTO.java
  src/main/java/org/lxdproject/lxd/correction/entity/mapping/MemberSavedCorrection.java
  src/main/java/org/lxdproject/lxd/correction/service/CorrectionService.java
  src/main/java/org/lxdproject/lxd/correction/service/MemberSavedCorrectionService.java
Labels: ✨feat, 서머/서현

#66 [FEATURE] 내가 작성한 일기 수정 API 구현
  src/main/java/org/lxdproject/lxd/apiPayload/code/status/ErrorStatus.java
  src/main/java/org/lxdproject/lxd/config/AwsS3Config.java
  src/main/java/org/lxdproject/lxd/diary/controller/DiaryApi.java
  src/main/java/org/lxdproject/lxd/diary/controller/DiaryController.java
  src/main/java/org/lxdproject/lxd/diary/entity/Diary.java
  src/main/java/org/lxdproject/lxd/diary/entity/Question.java
  src/main/java/org/lxdproject/lxd/diary/service/DiaryService.java
Labels: ✨feat, 만두/민지

#73 [FEATURE] 일기 댓글 조회/삭제 API 구현
  src/main/java/org/lxdproject/lxd/diarycomment/controller/DiaryCommentApi.java
  src/main/java/org/lxdproject/lxd/diarycomment/controller/DiaryCommentController.java
  src/main/java/org/lxdproject/lxd/diarycomment/dto/DiaryCommentDeleteResponseDTO.java
  src/main/java/org/lxdproject/lxd/diarycomment/dto/DiaryCommentRequestDTO.java
  src/main/java/org/lxdproject/lxd/diarycomment/dto/DiaryCommentResponseDTO.java
  src/main/java/org/lxdproject/lxd/diarycomment/entity/DiaryComment.java
  src/main/java/org/lxdproject/lxd/diarycomment/repository/DiaryCommentRepository.java
  src/main/java/org/lxdproject/lxd/diarycomment/service/DiaryCommentService.java
  src/main/java/org/lxdproject/lxd/diarycommentlike/repository/DiaryCommentLikeRepository.java
  src/main/java/org/lxdproject/lxd/diarycommentlike/service/DiaryCommentLikeService.java
Labels: ✨feat, ♻️Refactor

#78 [FEATURE] 구글 로그인 구현
  src/main/java/org/lxdproject/lxd/auth/controller/AuthRestController.java
  src/main/java/org/lxdproject/lxd/auth/dto/AuthRequestDTO.java
  src/main/java/org/lxdproject/lxd/auth/dto/AuthResponseDTO.java
  src/main/java/org/lxdproject/lxd/auth/dto/oauth/GoogleTokenResponse.java
  src/main/java/org/lxdproject/lxd/auth/dto/oauth/GoogleUserInfo.java
  src/main/java/org/lxdproject/lxd/auth/dto/oauth/OAuthUserInfo.java
  src/main/java/org/lxdproject/lxd/auth/service/AuthService.java
  src/main/java/org/lxdproject/lxd/auth/service/oauth/GoogleOAuthClient.java
  src/main/java/org/lxdproject/lxd/auth/service/oauth/OAuthClient.java
  src/main/java/org/lxdproject/lxd/config/RestTemplateConfig.java
  src/main/java/org/lxdproject/lxd/config/security/SecurityConfig.java
  src/main/java/org/lxdproject/lxd/member/converter/MemberConverter.java
  src/main/java/org/lxdproject/lxd/member/dto/MemberRequestDTO.java
Labels: ✨feat, 밤하늘/준현

#83 [FEATURE] 교정 좋아요 API 구현
  src/main/java/org/lxdproject/lxd/correction/controller/CorrectionApi.java
  src/main/java/org/lxdproject/lxd/correction/controller/CorrectionRestController.java
  src/main/java/org/lxdproject/lxd/correction/dto/CorrectionResponseDTO.java
  src/main/java/org/lxdproject/lxd/correction/dto/MemberSavedCorrectionRequestDTO.java
  src/main/java/org/lxdproject/lxd/correction/entity/Correction.java
  src/main/java/org/lxdproject/lxd/correction/repository/CorrectionRepository.java
  src/main/java/org/lxdproject/lxd/correction/repository/MemberSavedCorrectionRepository.java
  src/main/java/org/lxdproject/lxd/correction/service/CorrectionService.java
  src/main/java/org/lxdproject/lxd/correction/service/MemberSavedCorrectionService.java
  src/main/java/org/lxdproject/lxd/diarycomment/service/DiaryCommentService.java
Labels: ✨feat, 서머/서현

#88 [FIX] 교정 Auth 오류 수정
  src/main/java/org/lxdproject/lxd/correction/controller/CorrectionApi.java
  src/main/java/org/lxdproject/lxd/correction/controller/CorrectionRestController.java
  src/main/java/org/lxdproject/lxd/correction/service/CorrectionService.java
Labels: 🐛fix, 서머/서현

#90 [FIX] 전 도메인 에러 및 버그 해결
  src/main/java/org/lxdproject/lxd/apiPayload/code/exception/handler/CommentHandler.java
  src/main/java/org/lxdproject/lxd/apiPayload/code/exception/handler/TempHandler.java
  src/main/java/org/lxdproject/lxd/apiPayload/code/status/ErrorStatus.java
  src/main/java/org/lxdproject/lxd/auth/controller/AuthController.java
  src/main/java/org/lxdproject/lxd/auth/service/AuthService.java
  src/main/java/org/lxdproject/lxd/common/dto/ImageResponseDTO.java
  src/main/java/org/lxdproject/lxd/common/entity/BaseEntity.java
  src/main/java/org/lxdproject/lxd/common/service/ImageService.java
  src/main/java/org/lxdproject/lxd/correction/controller/CorrectionController.java
  src/main/java/org/lxdproject/lxd/correction/dto/MemberSavedCorrectionResponseDTO.java
  src/main/java/org/lxdproject/lxd/correction/service/CorrectionService.java
  src/main/java/org/lxdproject/lxd/correction/service/MemberSavedCorrectionService.java
  src/main/java/org/lxdproject/lxd/diary/controller/DiaryApi.java
  src/main/java/org/lxdproject/lxd/diary/controller/DiaryController.java
  src/main/java/org/lxdproject/lxd/diary/dto/DiaryDetailResponseDTO.java
  src/main/java/org/lxdproject/lxd/diary/dto/DiarySliceResponseDTO.java
  src/main/java/org/lxdproject/lxd/diary/dto/DiaryStatsResponseDTO.java
  src/main/java/org/lxdproject/lxd/diary/dto/DiarySummaryResponseDTO.java
  src/main/java/org/lxdproject/lxd/diary/entity/Diary.java
  src/main/java/org/lxdproject/lxd/diary/entity/mapping/DiaryLike.java
  src/main/java/org/lxdproject/lxd/diary/repository/DiaryRepository.java
  src/main/java/org/lxdproject/lxd/diary/repository/DiaryRepository/DiaryRepositoryCustom.java
  src/main/java/org/lxdproject/lxd/diary/repository/DiaryRepositoryCustom.java
  src/main/java/org/lxdproject/lxd/diary/repository/DiaryRepositoryImpl.java
  src/main/java/org/lxdproject/lxd/diary/repository/QuestionRepository.java
  src/main/java/org/lxdproject/lxd/diary/service/DiaryService.java
  src/main/java/org/lxdproject/lxd/diarycomment/controller/DiaryCommentApi.java
  src/main/java/org/lxdproject/lxd/diarycomment/controller/DiaryCommentController.java
  src/main/java/org/lxdproject/lxd/diarycomment/converter/DiaryCommentConverter.java
  src/main/java/org/lxdproject/lxd/diarycomment/dto/DiaryCommentResponseDTO.java
  src/main/java/org/lxdproject/lxd/diarycomment/entity/DiaryComment.java
  src/main/java/org/lxdproject/lxd/diarycomment/repository/DiaryCommentRepository.java
  src/main/java/org/lxdproject/lxd/diarycomment/service/DiaryCommentService.java
  src/main/java/org/lxdproject/lxd/diarycommentlike/repository/DiaryCommentLikeRepository.java
  src/main/java/org/lxdproject/lxd/member/controller/MemberController.java
  src/main/java/org/lxdproject/lxd/member/entity/Member.java
  src/main/java/org/lxdproject/lxd/test/controller/TestController.java
Labels: 🐛fix, ♻️Refactor, 슝슝/소윤

#94 [FEATURE] 프로필 조회 API 구현
  src/main/java/org/lxdproject/lxd/member/controller/MemberController.java
  src/main/java/org/lxdproject/lxd/member/dto/MemberResponseDTO.java
  src/main/java/org/lxdproject/lxd/member/service/MemberService.java
Labels: ✨feat, 서머/서현

#98 [REFACTOR] AuthApi 도입
  src/main/java/org/lxdproject/lxd/auth/controller/AuthApi.java
  src/main/java/org/lxdproject/lxd/auth/controller/AuthController.java
  src/main/java/org/lxdproject/lxd/auth/dto/AuthRequestDTO.java
Labels: ♻️Refactor

#119 [REFACTOR] 회원가입 API 수정
  src/main/java/org/lxdproject/lxd/apiPayload/code/status/ErrorStatus.java
  src/main/java/org/lxdproject/lxd/member/controller/MemberApi.java
  src/main/java/org/lxdproject/lxd/member/controller/MemberController.java
  src/main/java/org/lxdproject/lxd/member/converter/MemberConverter.java
  src/main/java/org/lxdproject/lxd/member/dto/MemberRequestDTO.java
  src/main/java/org/lxdproject/lxd/member/dto/MemberResponseDTO.java
  src/main/java/org/lxdproject/lxd/member/repository/MemberRepository.java
  src/main/java/org/lxdproject/lxd/member/service/MemberService.java
Labels: ♻️Refactor, 밤하늘/준현

#128 [FEATURE] FriendResponseDTO에 ProfileImage 필드 추가
  src/main/java/org/lxdproject/lxd/member/dto/FriendResponseDTO.java
  src/main/java/org/lxdproject/lxd/member/service/FriendService.java
Labels: ✨feat, 만두/민지

#133 [FEATURE] 내가 작성한 일기 수정 API 에서 본문(content)의 전후 diff 계산
  README.md
  src/main/java/name/fraser/neil/plaintext/diff_match_patch.java
  src/main/java/org/lxdproject/lxd/common/util/S3Uploader.java
  src/main/java/org/lxdproject/lxd/diary/dto/DiaryDetailResponseDTO.java
  src/main/java/org/lxdproject/lxd/diary/service/DiaryService.java
Labels: ✨feat, 만두/민지

#132 [FEATURE] 프로필 수정 API 구현
  src/main/java/org/lxdproject/lxd/apiPayload/code/status/ErrorStatus.java
  src/main/java/org/lxdproject/lxd/member/controller/MemberApi.java
  src/main/java/org/lxdproject/lxd/member/controller/MemberController.java
  src/main/java/org/lxdproject/lxd/member/dto/MemberRequestDTO.java
  src/main/java/org/lxdproject/lxd/member/entity/Member.java
  src/main/java/org/lxdproject/lxd/member/service/MemberService.java
Labels: ✨feat, 서머/서현

#136 [REFACTOR] 내가 제공한 교정 Response 추가
  src/main/java/org/lxdproject/lxd/correction/dto/CorrectionResponseDTO.java
  src/main/java/org/lxdproject/lxd/correction/service/CorrectionService.java
Labels: ♻️Refactor, 서머/서현
