Repository LXD-UMC-8th/BE-LXD, pull requests merged in 2025-08, with the labels that each got.

#142 [FEATURE] 다른 사용자의 일기 정보 요약 API의 반환값 dto에 FriendRequestStatus enum 내용 추가
  src/main/java/org/lxdproject/lxd/diary/controller/DiaryController.java
  src/main/java/org/lxdproject/lxd/diary/dto/MemberDiarySummaryResponseDTO.java
  src/main/java/org/lxdproject/lxd/diary/service/DiaryService.java
Labels: ✨feat, 만두/민지

#143 [FEATURE] 친구 목록 조회 API, 친구 요청 목록 조회 API에 각각 친구수, 요청수 필드 동일하게 추가
  src/main/java/org/lxdproject/lxd/member/dto/FriendListResponseDTO.java
  src/main/java/org/lxdproject/lxd/member/dto/FriendRequestListResponseDTO.java
  src/main/java/org/lxdproject/lxd/member/service/FriendService.java
Labels: ✨feat, 만두/민지

#146 [REFACTOR] 로그인 API 수정
  src/main/java/org/lxdproject/lxd/apiPayload/code/status/ErrorStatus.java
  src/main/java/org/lxdproject/lxd/auth/converter/AuthConverter.java
  src/main/java/org/lxdproject/lxd/auth/dto/AuthResponseDTO.java
  src/main/java/org/lxdproject/lxd/auth/enums/TokenType.java
  src/main/java/org/lxdproject/lxd/auth/service/AuthService.java
  src/main/java/org/lxdproject/lxd/config/security/jwt/JwtTokenProvider.java
  src/main/java/org/lxdproject/lxd/member/entity/Member.java
Labels: ♻️Refactor, 밤하늘/준현

#149 [FEATURE] 친구 요청 거절, 친구 요청 취소 API 구현
  src/main/java/org/lxdproject/lxd/apiPayload/code/status/ErrorStatus.java
  src/main/java/org/lxdproject/lxd/member/controller/FriendApi.java
  src/main/java/org/lxdproject/lxd/member/controller/FriendController.java
  src/main/java/org/lxdproject/lxd/member/controller/MemberApi.java
  src/main/java/org/lxdproject/lxd/member/controller/MemberController.java
  src/main/java/org/lxdproject/lxd/member/dto/FriendRequestCancelRequestDTO.java
  src/main/java/org/lxdproject/lxd/member/dto/FriendRequestRefuseRequestDTO.java
  src/main/java/org/lxdproject/lxd/member/entity/FriendRequest.java
  src/main/java/org/lxdproject/lxd/member/entity/enums/FriendRequestStatus.java
  src/main/java/org/lxdproject/lxd/member/repository/FriendRequestRepository.java
  src/main/java/org/lxdproject/lxd/member/service/FriendService.java
Labels: ✨feat, 만두/민지

#152 [FEATURE] logout API 구현
  src/main/java/org/lxdproject/lxd/apiPayload/code/status/ErrorStatus.java
  src/main/java/org/lxdproject/lxd/auth/controller/AuthApi.java
  src/main/java/org/lxdproject/lxd/auth/controller/AuthController.java
  src/main/java/org/lxdproject/lxd/auth/dto/AuthRequestDTO.java
  src/main/java/org/lxdproject/lxd/auth/service/AuthService.java
  src/main/java/org/lxdproject/lxd/config/security/SecurityConfig.java
  src/main/java/org/lxdproject/lxd/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/org/lxdproject/lxd/config/security/jwt/JwtTokenProvider.java
Labels: ✨feat, 밤하늘/준현

#154 [FIX] 이메일 전송 API 수정
  src/main/java/org/lxdproject/lxd/apiPayload/code/status/ErrorStatus.java
  src/main/java/org/lxdproject/lxd/auth/controller/AuthApi.java
  src/main/java/org/lxdproject/lxd/auth/controller/AuthController.java
  src/main/java/org/lxdproject/lxd/auth/dto/AuthResponseDTO.java
  src/main/java/org/lxdproject/lxd/auth/service/AuthService.java
  src/main/java/org/lxdproject/lxd/config/security/SecurityConfig.java
Labels: 🐛fix, 밤하늘/준현

#161 [REFACTOR] 인증 도메인 점검 완료
  src/main/java/org/lxdproject/lxd/auth/service/AuthService.java
  src/main/java/org/lxdproject/lxd/diary/repository/DiaryRepositoryImpl.java
  src/main/java/org/lxdproject/lxd/diarycomment/converter/DiaryCommentConverter.java
  src/main/java/org/lxdproject/lxd/diarycomment/dto/DiaryCommentDeleteResponseDTO.java
  src/main/java/org/lxdproject/lxd/diarycomment/dto/DiaryCommentResponseDTO.java
  src/main/java/org/lxdproject/lxd/diarycomment/service/DiaryCommentService.java
Labels: ✨feat, ♻️Refactor, 슝슝/소윤

#163 [FIX] 이메일 인증 후 redirect되는 uri 수정
  src/main/java/org/lxdproject/lxd/auth/service/AuthService.java
Labels: 🐛fix, 밤하늘/준현

#165 [FEATURE] 일기 좋아요 설정/해제 구현
  src/main/java/org/lxdproject/lxd/config/security/SecurityConfig.java
  src/main/java/org/lxdproject/lxd/diarylike/controller/DiaryLikeApi.java
  src/main/java/org/lxdproject/lxd/diarylike/controller/DiaryLikeController.java
  src/main/java/org/lxdproject/lxd/diarylike/dto/DiaryLikeRequestDTO.java
  src/main/java/org/lxdproject/lxd/diarylike/dto/DiaryLikeResponseDTO.java
  src/main/java/org/lxdproject/lxd/diarylike/repository/DiaryLikeRepository.java
  src/main/java/org/lxdproject/lxd/diarylike/service/DiaryLikeService.java
  src/main/java/org/lxdproject/lxd/member/controller/MemberApi.java
Labels: ✨feat, 밤하늘/준현

#169 [FIX] 친구 도메인 API 저장 및 조회 방식 통일
  src/main/java/org/lxdproject/lxd/diary/dto/MemberDiarySummaryResponseDTO.java
  src/main/java/org/lxdproject/lxd/diary/service/DiaryService.java
  src/main/java/org/lxdproject/lxd/member/controller/FriendApi.java
  src/main/java/org/lxdproject/lxd/member/controller/FriendController.java
  src/main/java/org/lxdproject/lxd/member/dto/FriendListResponseDTO.java
  src/main/java/org/lxdproject/lxd/member/dto/FriendRequestListResponseDTO.java
  src/main/java/org/lxdproject/lxd/member/repository/FriendRepository.java
  src/main/java/org/lxdproject/lxd/member/repository/FriendRepositoryImpl.java
  src/main/java/org/lxdproject/lxd/member/repository/FriendRequestRepository.java
  src/main/java/org/lxdproject/lxd/member/service/FriendService.java
Labels: 🐛fix, 만두/민지

#178 [FIX] Path 오류 수정
  src/main/java/org/lxdproject/lxd/auth/service/AuthService.java
Labels: 🐛fix, 밤하늘/준현

#179 [FIX] Cors 에러 및 친구 요청 목록 조회 성능 개선
  src/main/java/org/lxdproject/lxd/config/security/SecurityConfig.java
  src/main/java/org/lxdproject/lxd/diary/dto/MemberDiarySummaryResponseDTO.java
  src/main/java/org/lxdproject/lxd/diary/repository/DiaryRepositoryImpl.java
  src/main/java/org/lxdproject/lxd/diary/service/DiaryService.java
  src/main/java/org/lxdproject/lxd/diarycomment/service/DiaryCommentService.java
  src/main/java/org/lxdproject/lxd/friend/controller/FriendApi.java
  src/main/java/org/lxdproject/lxd/friend/controller/FriendController.java
  src/main/java/org/lxdproject/lxd/friend/dto/FriendListResponseDTO.java
  src/main/java/org/lxdproject/lxd/friend/dto/FriendMessageResponseDTO.java
  src/main/java/org/lxdproject/lxd/friend/dto/FriendRequestAcceptRequestDTO.java
  src/main/java/org/lxdproject/lxd/friend/dto/FriendRequestCancelRequestDTO.java
  src/main/java/org/lxdproject/lxd/friend/dto/FriendRequestCreateRequestDTO.java
  src/main/java/org/lxdproject/lxd/friend/dto/FriendRequestListResponseDTO.java
  src/main/java/org/lxdproject/lxd/friend/dto/FriendRequestRefuseRequestDTO.java
  src/main/java/org/lxdproject/lxd/friend/dto/FriendResponseDTO.java
  src/main/java/org/lxdproject/lxd/friend/entity/FriendRequest.java
  src/main/java/org/lxdproject/lxd/friend/entity/Friendship.java
  src/main/java/org/lxdproject/lxd/friend/entity/enums/FriendRequestStatus.java
  src/main/java/org/lxdproject/lxd/friend/repository/FriendRepository.java
  src/main/java/org/lxdproject/lxd/friend/repository/FriendRepositoryImpl.java
  src/main/java/org/lxdproject/lxd/friend/repository/FriendRequestRepository.java
  src/main/java/org/lxdproject/lxd/friend/service/FriendService.java
  src/main/java/org/lxdproject/lxd/member/repository/FriendRequestRepository.java
Labels: ♻️Refactor, 슝슝/소윤

#182 [FEATURE] 친구 찾기 기능 구현
  src/main/java/org/lxdproject/lxd/apiPayload/code/status/ErrorStatus.java
  src/main/java/org/lxdproject/lxd/common/dto/PageResponse.java
  src/main/java/org/lxdproject/lxd/config/redis/RedisConfig.java
  src/main/java/org/lxdproject/lxd/friend/controller/FriendApi.java
  src/main/java/org/lxdproject/lxd/friend/controller/FriendController.java
  src/main/java/org/lxdproject/lxd/friend/dto/FriendSearchResponseDTO.java
  src/main/java/org/lxdproject/lxd/friend/entity/Friendship.java
  src/main/java/org/lxdproject/lxd/friend/repository/FriendRepository.java
  src/main/java/org/lxdproject/lxd/friend/repository/FriendRepositoryCustom.java
  src/main/java/org/lxdproject/lxd/friend/repository/FriendRepositoryImpl.java
  src/main/java/org/lxdproject/lxd/friend/repository/FriendRequestRepository.java
  src/main/java/org/lxdproject/lxd/friend/service/FriendService.java
  src/main/java/org/lxdproject/lxd/infra/redis/RedisKeyPrefix.java
  src/main/java/org/lxdproject/lxd/infra/redis/RedisService.java
  src/main/java/org/lxdproject/lxd/member/repository/MemberRepository.java
  src/main/java/org/lxdproject/lxd/member/repository/MemberRepositoryCustom.java
  src/main/java/org/lxdproject/lxd/member/repository/MemberRepositoryImpl.java
Labels: ✨feat, 슝슝/소윤

#183 [RELEASE] 친구 도메인 구현 완료
  src/main/java/org/lxdproject/lxd/apiPayload/code/status/ErrorStatus.java
  src/main/java/org/lxdproject/lxd/common/dto/PageResponse.java
  src/main/java/org/lxdproject/lxd/config/redis/RedisConfig.java
  src/main/java/org/lxdproject/lxd/friend/controller/FriendApi.java
  src/main/java/org/lxdproject/lxd/friend/controller/FriendController.java
  src/main/java/org/lxdproject/lxd/friend/dto/FriendSearchResponseDTO.java
  src/main/java/org/lxdproject/lxd/friend/entity/Friendship.java
  src/main/java/org/lxdproject/lxd/friend/repository/FriendRepository.java
  src/main/java/org/lxdproject/lxd/friend/repository/FriendRepositoryCustom.java
  src/main/java/org/lxdproject/lxd/friend/repository/FriendRepositoryImpl.java
  src/main/java/org/lxdproject/lxd/friend/repository/FriendRequestRepository.java
  src/main/java/org/lxdproject/lxd/friend/service/FriendService.java
  src/main/java/org/lxdproject/lxd/infra/redis/RedisKeyPrefix.java
  src/main/java/org/lxdproject/lxd/infra/redis/RedisService.java
  src/main/java/org/lxdproject/lxd/member/repository/MemberRepository.java
  src/main/java/org/lxdproject/lxd/member/repository/MemberRepositoryCustom.java
  src/main/java/org/lxdproject/lxd/member/repository/MemberRepositoryImpl.java
Labels: ✨feat, 만두/민지

#189 [FEATURE] 비밀번호 변경 API 구현
  src/main/java/org/lxdproject/lxd/apiPayload/code/status/ErrorStatus.java
  src/main/java/org/lxdproject/lxd/auth/dto/AuthRequestDTO.java
  src/main/java/org/lxdproject/lxd/auth/enums/VerificationType.java
  src/main/java/org/lxdproject/lxd/auth/service/AuthService.java
  src/main/java/org/lxdproject/lxd/config/security/SecurityConfig.java
  src/main/java/org/lxdproject/lxd/infra/redis/RedisService.java
  src/main/java/org/lxdproject/lxd/member/controller/MemberApi.java
  src/main/java/org/lxdproject/lxd/member/controller/MemberController.java
  src/main/java/org/lxdproject/lxd/member/dto/MemberRequestDTO.java
  src/main/java/org/lxdproject/lxd/member/entity/Member.java
  src/main/java/org/lxdproject/lxd/member/service/MemberService.java
  src/main/resources/templates/password.html
Labels: ✨feat, 밤하늘/준현

#191 [FIX] diary/liked 엔드포인트의 isLiked 필드 수정
  src/main/java/org/lxdproject/lxd/diary/repository/DiaryRepositoryImpl.java
Labels: 🐛fix, 만두/민지

#201 [REFACTOR] 특정 이벤트 발생시 알림 삭제 로직 추가
  src/main/java/org/lxdproject/lxd/friend/service/FriendService.java
  src/main/java/org/lxdproject/lxd/notification/dto/NotificationDeleteEvent.java
  src/main/java/org/lxdproject/lxd/notification/dto/NotificationReadUpdateEvent.java
  src/main/java/org/lxdproject/lxd/notification/entity/Notification.java
  src/main/java/org/lxdproject/lxd/notification/repository/NotificationRepositoryCustom.java
  src/main/java/org/lxdproject/lxd/notification/repository/NotificationRepositoryImpl.java
  src/main/java/org/lxdproject/lxd/notification/service/SseEmitterService.java
Labels: ✨feat, ♻️Refactor, 슝슝/소윤

#206 [FEATURE] 사용자 정보란에 모국어, 학습언어 추가하기
  src/main/java/org/lxdproject/lxd/diary/dto/DiarySummaryResponseDTO.java
  src/main/java/org/lxdproject/lxd/diary/dto/MemberDiarySummaryResponseDTO.java
  src/main/java/org/lxdproject/lxd/diary/repository/DiaryRepositoryCustom.java
  src/main/java/org/lxdproject/lxd/diary/repository/DiaryRepositoryImpl.java
  src/main/java/org/lxdproject/lxd/diary/service/DiaryService.java
Labels: ✨feat, 만두/민지

#202 [FEATURE] 내 일기가 탐색탭에 노출되지 않도록 수정
  src/main/java/org/lxdproject/lxd/diary/repository/DiaryRepositoryImpl.java
Labels: ✨feat, 만두/민지

#217 [FIX] DiaryRepository에서 countByMemberId → countByMemberIdAndDeletedAtI…
  src/main/java/org/lxdproject/lxd/diary/repository/DiaryRepository.java
  src/main/java/org/lxdproject/lxd/diary/service/DiaryService.java
Labels: 🐛fix, 만두/민지

#226 [REFACTOR] 일기 댓글 조회 수정
  src/main/java/org/lxdproject/lxd/correctioncomment/controller/CorrectionCommentController.java
  src/main/java/org/lxdproject/lxd/correctioncomment/service/CorrectionCommentService.java
  src/main/java/org/lxdproject/lxd/diarycomment/controller/DiaryCommentApi.java
  src/main/java/org/lxdproject/lxd/diarycomment/controller/DiaryCommentController.java
  src/main/java/org/lxdproject/lxd/diarycomment/dto/DiaryCommentResponseDTO.java
  src/main/java/org/lxdproject/lxd/diarycomment/repository/DiaryCommentRepository.java
  src/main/java/org/lxdproject/lxd/diarycomment/repository/DiaryCommentRepositoryCustom.java
  src/main/java/org/lxdproject/lxd/diarycomment/repository/DiaryCommentRepositoryImpl.java
  src/main/java/org/lxdproject/lxd/diarycomment/service/DiaryCommentService.java
  src/main/java/org/lxdproject/lxd/diarycommentlike/repository/DiaryCommentLikeRepository.java
Labels: ♻️Refactor, 슝슝/소윤

#228 [FIX] 조회 API의 정렬 수정
  src/main/java/org/lxdproject/lxd/correction/service/CorrectionService.java
  src/main/java/org/lxdproject/lxd/friend/repository/FriendRequestRepository.java
  src/main/java/org/lxdproject/lxd/notification/service/NotificationService.java
Labels: 🐛fix, 슝슝/소윤

#230 [FIX] GetEmailByToken 메소드 버그 수정
  src/main/java/org/lxdproject/lxd/auth/service/AuthService.java
  src/main/java/org/lxdproject/lxd/infra/redis/RedisService.java
Labels: 🐛fix, 슝슝/소윤

#246 [FIX] 멤버의 system language로 알림 메시지 언어 설정
  src/main/java/org/lxdproject/lxd/notification/service/NotificationService.java
Labels: 🐛fix, 슝슝/소윤

#250 [FIX] 알림 전송 외 이벤트 발생시 flush 추가
  src/main/java/org/lxdproject/lxd/friend/service/FriendService.java
  src/main/java/org/lxdproject/lxd/notification/service/NotificationService.java
Labels: 🐛fix, 슝슝/소윤

#255 [FIX] 친구 관계 조회 및 삭제 로직 수정
  src/main/java/org/lxdproject/lxd/friend/repository/FriendRepositoryCustom.java
  src/main/java/org/lxdproject/lxd/friend/repository/FriendRepositoryImpl.java
  src/main/java/org/lxdproject/lxd/friend/service/FriendService.java
Labels: 🐛fix, 슝슝/소윤
